export const SERVER_URL = process.env.REACT_APP_SERVER_URL;
export const PUBNUB_PUBLISH_KEY = process.env.REACT_APP_PUBNUB_PUBLISH_KEY;
export const PUBNUB_SUBSCRIBE_KEY = process.env.REACT_APP_PUBNUB_SUBSCRIBE_KEY;
export const PUBNUB_SECRET_KEY = process.env.REACT_APP_PUBNUB_SECRET_KEY;
